import { ArtStyleOption, ToneOption } from '../types/comic';

export const ART_STYLES: ArtStyleOption[] = [
  {
    id: 'classic-comic',
    name: 'Classic Comic Book',
    tagline: 'Vintage 1970s Silver Age comic style',
    description: 'Crisp black ink outlines, authentic Ben-Day halftone dot shading, vivid primary CMYK colors, dynamic comic book action hatching.',
    promptModifier: 'vintage 1970s American comic book art style, authentic Ben-Day dots halftone pattern, dynamic crosshatching, bold black ink lines, classic Marvel/DC Silver Age aesthetics, rich comic flat colors, expressive dramatic composition',
    badgeColor: 'bg-yellow-400 text-black border-black',
    icon: '💥',
  },
  {
    id: 'anime-manga',
    name: 'Anime & Manga',
    tagline: 'Japanese manga & modern anime aesthetic',
    description: 'Sharp precision line art, screentones, expressive eyes, speed action lines, dramatic cinematic angles, stylized hair and vibrant cel shading.',
    promptModifier: 'modern Japanese anime and manga style, vibrant key visual art, sharp ink outlines, screentone shading, expressive anime eyes, cinematic dramatic lighting, studio MAPPA/Ufotable aesthetic, crisp details',
    badgeColor: 'bg-pink-400 text-black border-black',
    icon: '✨',
  },
  {
    id: 'graphic-novel',
    name: 'Dark Graphic Novel',
    tagline: 'Atmospheric noir & cinematic ink',
    description: 'Moody chiaroscuro lighting, heavy textured shadows, gritty graphic novel linework reminiscent of Frank Miller and Mike Mignola.',
    promptModifier: 'gritty graphic novel art style, deep chiaroscuro shadows, high contrast black ink, moody cinematic lighting, Frank Miller and Hellboy comic aesthetic, mature atmospheric tones',
    badgeColor: 'bg-stone-800 text-amber-100 border-black',
    icon: '🦇',
  },
  {
    id: 'cartoon',
    name: 'Saturday Morning Cartoon',
    tagline: 'Playful cel-shaded animation style',
    description: 'Bold rounded outlines, bouncy energetic character poses, whimsical bright colors, exaggerated comical expressions and fun stylized backgrounds.',
    promptModifier: 'Saturday morning cartoon style, vibrant cel-shaded colors, playful bouncy character design, thick smooth outlines, whimsical animated series look, humorous exaggerated expression, bright inviting atmosphere',
    badgeColor: 'bg-emerald-400 text-black border-black',
    icon: '🎨',
  },
  {
    id: 'superhero',
    name: 'Superhero Epic',
    tagline: 'High-octane heroic comic illustration',
    description: 'Heroic proportions, dramatic rim lighting, intense dynamic motion blur, detailed rendering, epic cinematic splash-page grandeur.',
    promptModifier: 'modern epic superhero comic book illustration, dynamic high-angle action pose, dramatic rim lighting, intricate inked details, Jim Lee and Alex Ross inspired comic realism, cinematic blockbuster scale',
    badgeColor: 'bg-red-500 text-white border-black',
    icon: '⚡',
  },
  {
    id: 'vintage-pulp',
    name: 'Vintage Pulp 1950s',
    tagline: 'Retro sci-fi & golden age comic look',
    description: 'Weathered yellowed paper grain, retro-futuristic styling, mid-century comic print artifacts, nostalgic warm palette.',
    promptModifier: '1950s golden age sci-fi pulp magazine illustration, retro comic aesthetic, distressed newsprint texture, limited warm vintage color palette, retro-futurism, nostalgic hand-drawn print',
    badgeColor: 'bg-amber-400 text-black border-black',
    icon: '🚀',
  },
  {
    id: 'webtoon',
    name: 'Modern Webtoon / Manhwa',
    tagline: 'Clean digital manhwa art style',
    description: 'Smooth digital gradients, luminous magic particle effects, crisp clean vector lines, polished modern Korean webtoon art.',
    promptModifier: 'Korean webtoon manhwa art style, Solo Leveling aesthetic, vibrant glowing lighting effects, clean digital ink, radiant highlights, high production value manhwa illustration',
    badgeColor: 'bg-indigo-400 text-white border-black',
    icon: '🌟',
  },
];

export const TONES: ToneOption[] = [
  {
    id: 'funny',
    name: 'Funny & Light-hearted',
    description: 'Witty banter, slapstick humor, comical misunderstandings, and cheerful punchlines.',
    emoji: '😂',
  },
  {
    id: 'dramatic',
    name: 'Dramatic & Epic',
    description: 'High emotional stakes, intense confrontation, profound dialogue, and heroic grit.',
    emoji: '🎭',
  },
  {
    id: 'action',
    name: 'High-Energy Action',
    description: 'Fast-paced combat, adrenaline stunts, explosive sound effects, and heroic showdowns.',
    emoji: '🔥',
  },
  {
    id: 'mystery',
    name: 'Mystery & Noir',
    description: 'Clues, cryptic riddles, suspicious shadows, plot twists, and investigative intrigue.',
    emoji: '🔍',
  },
  {
    id: 'whimsical',
    name: 'Whimsical Fantasy',
    description: 'Magical wonder, fairy-tale charm, eccentric creatures, and enchanting adventures.',
    emoji: '🧚',
  },
  {
    id: 'scifi',
    name: 'Sci-Fi Adventure',
    description: 'High-tech gadgets, alien worlds, cyberpunk neon streets, and galactic quests.',
    emoji: '🛸',
  },
  {
    id: 'horror',
    name: 'Spooky & Creepy',
    description: 'Eerie suspense, strange encounters in the dark, thrilling scares, and spooky twists.',
    emoji: '👻',
  },
];

export const STORY_PRESETS = [
  {
    title: 'The Brave Fox of Whispering Woods',
    prompt: 'A brave young red fox discovers a glowing ancient crystal inside the heart of an enchanted forest, awakening a gentle tree spirit.',
    characterName: 'Rusty the Fox',
    characterDetails: 'A clever, spirited young red fox with a tattered green scout cape and glowing amber eyes',
    setting: 'Enchanted Whispering Forest with bioluminescent mushrooms and towering ancient oaks',
    tone: 'dramatic' as const,
    artStyle: 'anime-manga' as const,
    layoutStyle: 'grid-4' as const,
  },
  {
    title: 'Cosmic Pizza Delivery Disaster',
    prompt: 'An alien delivery driver tries to deliver an extra-dimensional hot cheese pizza while dodging space asteroids and hungry space monsters.',
    characterName: 'Blip',
    characterDetails: 'A goofy three-eyed blue alien wearing a stained retro pizza parlor apron and propeller cap',
    setting: 'Outer space asteroid belt with neon nebula gas and chaotic flying delivery saucers',
    tone: 'funny' as const,
    artStyle: 'classic-comic' as const,
    layoutStyle: 'strip-4' as const,
  },
  {
    title: 'Cyberpunk Noir: Neon Shadows',
    prompt: 'A cyborg detective follows a trail of encoded microchips in rain-soaked alleyways, uncovering a secret corporate conspiracy.',
    characterName: 'Detective Jax Vance',
    characterDetails: 'Weary private eye with a glowing cybernetic trench eye, smoking trenchcoat, and brass cyber-knuckles',
    setting: 'Rain-soaked dystopian megalopolis with towering holographic billboards and dark alleyways',
    tone: 'mystery' as const,
    artStyle: 'graphic-novel' as const,
    layoutStyle: 'graphic-6' as const,
  },
  {
    title: 'Captain Claws: Feline Avenger',
    prompt: 'A neighborhood cat who secretly has superhero powers thwarts a band of mischievous raccoon bank robbers.',
    characterName: 'Captain Claws (Barnaby)',
    characterDetails: 'A chubby ginger tuxedo cat wearing a tiny red mask and miniature heroic cape',
    setting: 'Suburban rooftops and backyard alleys under a bright sunny afternoon',
    tone: 'funny' as const,
    artStyle: 'cartoon' as const,
    layoutStyle: 'grid-4' as const,
  },
];
